# Generated by Django 4.2 on 2024-01-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
